### ISSUE TITLE
http://localhost:3000/traceur 404 (Not Found)

### ISSUE THREAD

**Issue by mateenQureshi** [shubhi1407/ng2-notify-popup#1]
Hello, 
i have loaded ng2-notify-popup package in my angular 2.4 project. but when i use to execute my project, i am getting this http://localhost:3000/traceur 404 (Not Found). As traceur is configured properly because i have working project, just after adding ng2-notify-popup my app becomes useless..
thank you!

**Comment by shubhi1407** [comment]
Can you try this in your SystemJS config 
```
map : {
...
   "traceur":"npm/tracuer/bin"
},
packages : {
    "traceur" : {
        main : "traceur"
      }
}
```
Have a look at this issue https://github.com/angular/angular/issues/11358 and the solution suggested by ericmdantas to use `.umd.js` for @angular

**Comment by mateenQureshi** [comment]
Hello, 
Thank you for your response. All angular packages are loaded using .umd.js, well i have added traceur.js into my app, but now getting traceur.js.map is missing, unfortunately i couldn't see any .js.map file in traceur package, please help me get out of this.

Thank you!

**Comment by shubhi1407** [comment]
Hi,
Sorry , but  this module is not supported in angular 2.x. This is because from Angular 4.0 onwards animation module is pulled into their own package, earlier it was in angular/core. 
You can find this breaking change here.
[https://github.com/angular/angular/blob/master/CHANGELOG.md#animation-package](https://github.com/angular/angular/blob/master/CHANGELOG.md#animation-package)
I would suggest you upgrade your project to latest angular, since we could see more breaking changes in coming days.
