### ISSUE TITLE
use angular4 angular-cli build in prod environment error

### ISSUE THREAD

**Issue by yinyihui** [shubhi1407/ng2-notify-popup#3]
In my angular4 project, it runs perfectly, but when i use "ng build -prod", it gose in errors like this:
ERROR in ng:///.../node_modules/ng2-notify-popup/ng2-notify-popup.d.ts.ɵa.html (2,26): Property 'location' does not exi
st on type 'NotificationComponent'.

ERROR in ng:///.../node_modules/ng2-notify-popup/ng2-notify-popup.d.ts.ɵa.html (2,26): Property 'location' does not exi
st on type 'NotificationComponent'.

i just use this component follow the README section Usage and use it in my AppModule.

plz help!

**Comment by shubhi1407** [comment]
[Fixed ](https://github.com/shubhi1407/ng2-notify-popup/commit/ce5216606855d6fbf7189680e88dc5f3b3deed7c)
Install latest version using
npm install --save ng2-notify-popup@latest

**Comment by yinyihui** [comment]
It works fine!Thanks a lot!

**Comment by yinyihui** [comment]
another error, when i build in prod, there are some warnings like this:
WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
656:37-48 "export 'ɵb' (imported as 'import29') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
1086:23-34 "export 'ɵb' (imported as 'import29') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/app/flow/steps/steps.component.ngfactory.ts
4734:93-104 "export 'ɵb' (imported as 'import17') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
245:36-46 "export 'ɵb' (imported as 'import1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
362:23-33 "export 'ɵb' (imported as 'import1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
495:37-47 "export 'ɵa' (imported as 'import1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
498:48-58 "export 'ɵa' (imported as 'import1') was not found in 'ng2-notify-popup'

then the main js has the error:
![image](https://cloud.githubusercontent.com/assets/13214503/26624832/b7f5be04-4624-11e7-9b5b-e0a74481bb8e.png)

**Comment by yinyihui** [comment]
Sorry to trouble again! There are some warnings when i build in prod, like this:
WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
656:37-48 "export 'ɵb' (imported as 'import29') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
1096:23-34 "export 'ɵb' (imported as 'import29') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
245:36-46 "export 'ɵb' (imported as 'import1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
362:23-33 "export 'ɵb' (imported as 'import1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
495:37-47 "export 'ɵa' (imported as 'import1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
498:48-58 "export 'ɵa' (imported as 'import1') was not found in 'ng2-notify-popup'

then the vendor gives the error:
![image](https://cloud.githubusercontent.com/assets/13214503/26625683/6ebd8d68-4627-11e7-8850-9094312531fc.png)

**Comment by verena91** [comment]
Hi @yinyihui @shubhi1407 I'm facing the same issue, did you solve the problem?

**Comment by yinyihui** [comment]
@verena91 I still have the problem，so i just change the component.

**Comment by yinyihui** [comment]
@verena91 I still have this problem，so I just change the component.

**Comment by vishnuindrabalan** [comment]
@verena91 @yinyihui @shubhi1407  I am also facing the same issue. How you fixed this?

**Comment by SantoshTirukkovilour** [comment]
Dear @shubhi1407 
Thank you for developing this component, it is very useful to use in angular application.

We are getting following issue when we tried to run the command  "ng build --prod". We appreciate your help if you can fix this issue, else let us know if you have any suggestions. So that we can try to fix it as you suggest.

WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
117:85-91 "export '?b' (imported as 'i25') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
117:93-99 "export '?b' (imported as 'i25') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
118:73-79 "export '?b' (imported as 'i25') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
29:22-27 "export '?b' (imported as 'i1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
29:29-34 "export '?b' (imported as 'i1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
75:142-147 "export '?a' (imported as 'i1') was not found in 'ng2-notify-popup'

WARNING in ./src/$$_gendir/~/ng2-notify-popup/ng2-notify-popup.ngfactory.ts
77:43-48 "export '?a' (imported as 'i1') was not found in 'ng2-notify-popup'

Appreciate your quick help
Thanks in Advance
Santosh Kumar

Appreciate others ( @vishnuindrabalan, @verena91, @yinyihui  ) also if you can help us to fix this issue.

**Comment by Hesesses** [comment]
Any news about this?

**Comment by bhushangahire** [comment]
+1 I am also getting the same issue. 

![image](https://user-images.githubusercontent.com/8351/31449858-a26a5566-ae6d-11e7-8a2b-c045d16b45ae.png)

**Comment by yinyihui** [comment]
@Hesesses @bhushangahire 
plz follow the issue #6
